---
  title: "Balance_Table"
author: ""
date: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r balance table}
# Load the following packages -------------
packages <- c("modelsummary", 
              "dplyr", 
              "haven")

if (!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman") 
pacman::p_load(packages, character.only = FALSE) # switch to TRUE to install packages 

# Load the sample data set --------------
data <- read_dta("/Users/koniks/Downloads/nlsw88.dta")
dir.create("Outputs", recursive = TRUE, showWarnings = TRUE) # to create a new folder 

# Create the data frame --------------
df_balance <- data %>% 
  select('Age in current year' = age, # replace the following with variable names 
         'Married' = married,
         'Union worker' = union, 
         'Hourly wage' = wage,
         'South' = south,
         collgrad # replace with variable indicating treatment status
         )

# Run the balance test and produce the table --------------
datasummary_balance(
  ~collgrad,
  data = df_balance,
  stars = TRUE, 
  title = "Balance by college graduation status (as treatment)",
  note = "Comparing college graduates vs non-graduates: Includes HHs with observations for endline and baseline", 
  output = "Outputs/balance.tex"
)

## Annex --------------

# To successfully view the table and reproduce the outputs, open the '.tex' file in any Latex editor, and add the following syntax:  

# \documentclass{article}

# % Required packages
# \usepackage{booktabs}    % For \toprule, \midrule, \bottomrule
# \usepackage{array}       % For column types
# \usepackage{geometry}

# % Optional: adjust page margins
# \geometry{margin=1in}

# \begin{document}

# Also, at the following syntax at the end of the file: 
# \end{document}
```
