---
pagetitle: "Bar Plots: Multiple Variables"
author: ""
date: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Objective ---------------
# Create clustered horizontal bar charts displaying baseline and midline outcomes for treatment and control groups. Include clustered bars for Papayas, Pineapples, and Coconuts.

# Install and load packages ---------------
packages <- c(
  "tidyverse",
  "haven",
  "forcats"
)

# Change to install = TRUE to install the required packages
pacman::p_load(packages, character.only = TRUE, install = FALSE)

# Load an example dataset ---------------
data <- readRDS("~/Documents/GitHub/DIME/Code_Reviews/CodeReview_r-econ-visual-library/r-econ-visual-library/Library/BarPlotsMultipleVariables.rds")

# Printing the first five rows of the data to visualize its structure before data wrangling
head(data)

# Data Dictionary ---------------
  ## Data Source: This graph uses fictional data created for the purpose of this graph. The fictional data comes from an imagined survey of tropical farmers participating in a fictional randomized control trial. 
  ## Tidy format? Yes
  ## Unit of Observation: Households
  ## Variables of interest
    # hh_id: Household identifier
    # round: Survey round id (baseline or midline) 
    # treatment_group: Treatment status id
    # w_Papaya: Annual Papaya Production
    # w_Pineapple: Annual Pineapple Production
    # w_Coconut: Annual Coconut Production 


# Data wrangling ---------------

# Collapse the dataset across each treatment group
collapsed_data <- 
  data %>% 
  group_by(treatment_group, 
           round) %>%
  summarise_at(vars(starts_with("w_")),
               ~ mean(., na.rm = T)) %>%
  ungroup()


# Printing the first five rows of the data to visualize its structure after collapsing
head(collapsed_data)

# Reshape data to long format 
reshaped_data <- collapsed_data %>% # Reshape crop variables to long format
                  pivot_longer( 
                    starts_with(c("w_")), # Select crop variables
                    names_to = "key", # Create crop identifiers
                    values_to = "value" # Record values in single column
                    ) %>%
                   mutate( # Merge data collection round and treatment variables together
                    round = replace(round, round == 1, "bl_"),
                    round = replace(round, round == 2, "ml_"),
                    round = fct_rev(as.factor(paste0(round, treatment_group))))


# Create a Graph ---------------
ggplot(reshaped_data, aes(x = key, y = value, fill = round)) +
  geom_bar( # Format bars 
    width = 0.6, 
    position = position_dodge(width = 0.6),
    stat = "identity", # Graph data as is
    alpha = .8 # Set transparency 
    ) +
  geom_text( # Add bar labels 
    aes(label = format(round(value, 1), nsmall = 1)), 
    position = position_dodge(width = 0.6), 
    hjust = -0.35
    ) +
  coord_flip(ylim = c(0, 150)) + # Make bars horizontal 
  geom_hline(yintercept = 0, alpha = 0.5) +
  scale_x_discrete(
    labels = c( 
      "w_Papaya" = "Papaya Prod", 
      "w_Pineapple" = "Pineapple Prod",
      "w_Coconut" = "Coconut Prod"
      )) +
  scale_fill_brewer( # Set color scheme 
    palette = "Set2",
    breaks = c("bl_0", "bl_1", "ml_0", "ml_1"), # Color bar clusters by data collection round and treatment status
    labels = c("Baseline-Control", "Baseline-Treatment", "Midline-Control", "Midline-Treatment")
    ) +
  ylab("Value") +
  theme_classic() +
  theme(
    axis.line.y = element_blank(),
    axis.title.y = element_blank(),
    axis.title.x = element_text(size = 14),
    axis.ticks.y = element_blank(),
    axis.text = element_text(size = 11),
    legend.title = element_blank(),
    legend.text = element_text(size = 10),
    legend.position = c(.84, .85), # Set legend to top right position 
    legend.box.background = element_rect(colour = "black")
    
    )

```

