---
author: ""
date: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r BarPlotsTwoVariables, fig.path = '../docs/figure/'}
# Objective ---------------
  # Create clustered bar charts displaying the percent of healthcare providers ordering correct treatment types by location and different observation types. 

# Install and load packages ---------------
packages <- c(
  "tidyverse",
  "haven",
  "latex2exp"
)

# Change to install = TRUE to install the required packages
pacman::p_load(packages, character.only = TRUE, install = FALSE)

# Load an example dataset ---------------
data <- read_dta("https://github.com/worldbank/r-econ-visual-library/raw/master/Library/Data/BarPlotsTwoVariables.dta")

# Printing the first five rows of the data to visualize its structure
head(data)

# Data Dictionary ---------------
  ## Data Source: Das, Jishnu, Liana Woskie, Ruma Rajbhandari, Kamran Abbasi, and Ashish Jha. “Rethinking assumptions about delivery of healthcare: implications for universal health coverage.” Bmj 361 (2018).
  ## Tidy format? Yes
  ## Unit of Observation: Group-level mean, collapsed by month observation type and study region
  ## Variables of interest:
    # study: Region of data collection
    # case: Medical treatment case identifier 
    # type: Observation type identifier
    # treat_correct: Mean of correctly-administered treatments by observation type in given region 





# Create a graph ---------------
ggplot(data, aes(fill = type, y = treat_correct, x = interaction(study, case))) +  
  # using the interaction function computes a factor that represents the interaction of the given factors (study and case in this example)
  geom_bar(width = 0.6, position = position_dodge(width = 0.8), stat = "identity") +
  geom_text(
    aes(label = format(round(treat_correct, 2), nsmall = 2)),  
    position = position_dodge(width = 0.8), 
    size = 4.5,
    vjust = -0.35
    ) +
  geom_hline(yintercept = 0) +
  annotate(
    "text", x = c(1, 2, 3), y = -0.02,
    label = levels(factor(data$study)), size = 5
    ) +
  annotate(
    "text", x = c(1, 2.5), y = -0.08,
    label = levels(factor((data$case))), size = 5
    ) + 
  theme_classic() +
  scale_fill_brewer(palette = "Set2", name = "Measurement") +
  ylab(TeX("Providers ordering correct treatment $\\rightarrow$")) + 
  theme(
    legend.position = 'bottom',
    legend.title = element_text(size = 15),
    legend.text = element_text(size = 15),
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_text(size = 12),
    axis.line = element_blank(),
    axis.title.y = element_text(size = 15)
    )
  
```
