---
title: 'How to contribute'
author: ""
date: ""
---

  + If you have suggestions of plots you would like to see in this library and are not currently here, you can open an [issue](https://github.com/worldbank/r-econ-visual-library/issues) describing your suggestion.
  + If you have graphs you would like to add to this library and are comfortable using GitHub, please feel free to make a fork and submit a [pull request](https://github.com/worldbank/r-econ-visual-library/pulls) to the develop branch for any additions you want to make, but please read the R Econ Visual Library contribution conventions section below first. If you are new to GitHub, start by reading the Bug reports and feature requests section below. 
  + If you have graphs you would like to add to this library and are new to GitHub, you can send an e-mail to dimeanalytics@worldbank.org with a zipped folder containing (1) the de-identified data used to create the plot and (2) the code that creates the plots from such data.
  
## Bug reports and feature requests

An easy but still very efficient way to provide any feedback on the content that does not require any GitHub knowledge is to create an [issue](https://github.com/worldbank/r-econ-visual-library/issues). You can read issues submitted by other users or create a new issue here. While the word issue has a negative connotation outside GitHub, it can be used for any kind of feedback. Please read already existing issues to check whether someone else has made the same suggestion or reported the same error before creating a new issue.

# R Econ Visual Library contribution conventions

In addition to using common GitHub practices, please follow these conventions to make it possible to keep an overview of the progress made to the code in this toolkit.

## Branch naming conventions

Please make pull requests to the `master` branch only if you wish to contribute to README, LICENSE or similar meta data files. If you wish to make a contribution to any Rmd files, then please do not use the `master` branch. If you wish to make a contribution to any Rmd files that we have published at least once, then please fork from and make your pull request to the `develop` branch.  If your addition is related to a specific issue in the repository, then create a new branch with a short and descriptive branch, for example `new-plot-scm`.

## Data visualization folder conventions

If you have a visualization code and you are familiar with the Rmarkdown language, please save the `.Rmd` file in `Library` folder and the data file used to create the figure in `Library/Data` folder. `.Rmd` files to create any types of figures (eg. bar plots, diff-in-diffs, etc.) can be placed in `Library` folder. Save figures in the appropriate folder in `Library/figure` folder. For example, when you save a bar plot, save the figure in `Library/figure/BarPlots`. If you cannot find an appropriate folder, please feel free to create a new folder for your figure in `Library/figure`. Also, save the output html file in `docs` folder (relative path from `Library` folder is `../docs`). For more details, please refer to other `.Rmd` files in `Library` folder.

If you have a visualization code in R and you are not familiar with Rmarkdown language, you can send an e-mail to dimeanalytics@worldbank.org with a zipped folder containing (1) the de-identified data used to create the plot and (2) the R script that creates the plots from such data.
