---
pagetitle: "Density Plots"
author: ""
date: ""
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview
Create a two-way color-coded density plot comparing agricultural revenue before and after treatment.

```{r DensityPlotAverage, fig.path = '../docs/figure/'}
# Install and load packages ---------------
packages <- c(
  "tidyverse",
  "haven"
)

# Change to install = TRUE to install the required packages
pacman::p_load(packages, character.only = TRUE, install = FALSE)

```

# Data

This graph uses fictional data created for the purpose of this graph. 

- `hh_id`: Household identifier
- `post`: Timing variable (pre/post treatment)
- `revenue`: Agricultural Revenue

- Unit of Observation: Households

```{r DensityPlotAverage, fig.path = '../docs/figure/'}
# Load an example dataset ---------------
data <- read_dta("https://github.com/worldbank/r-econ-visual-library/raw/master/Library/Data/DensityPlotAverage.dta")

# Printing the first five rows of the data to visualize its structure before data wrangling
head(data)

```

```{r DensityPlotAverage, fig.path = '../docs/figure/'}
# Data wrangling ---------------
data <- data %>%
  mutate(post = as.factor(.$post)) %>% 
  # using . "dot" lets you access the entire dataset. In this example, . refers to the data and .$post refers to the post variable in the entire dataset
  group_by(post) %>%
  mutate(mean_revenue = mean(revenue)) %>%
  ungroup()

# Printing the first five rows of the data to visualize its structure after data wrangling
head(data)

```

```{r DensityPlotAverage, fig.path = '../docs/figure/', message = FALSE, warning = FALSE}
# Create a graph ---------------
ggplot(data, aes(x = revenue, colour = post)) + # Use color instead of fill for the density plot
  geom_density(alpha = 0.1) +
  geom_vline( # Add dashed vertical lines to indicate means
    aes(xintercept = mean_revenue, colour = post), 
    linetype = "dashed", size = 0.3
    ) +
  theme_classic() +
  labs(
    x = "Agricultural Revenue (BRL thousands)",
    y = "Density"
  ) +
  scale_colour_discrete(labels = c("Pre-treatment", "Post-treatment")) +
  scale_color_brewer(palette = "Set2") + 
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 15),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    legend.position = "bottom"
    )

```

