---
pagetitle: "Density Plots: Cumulative Density Curves"
author: ""
date: ""
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r DensityCDF, fig.path = '../docs/figure/'}
# Objective ---------------
  # Create a two-way color-coded cumulative distribution function comparing agricultural revenue before and after treatment

# Install and load packages ---------------
packages <- c(
  "tidyverse",
  "haven",
  "labelled"
)

# Change to install = TRUE to install the required packages
pacman::p_load(packages, character.only = TRUE, install = FALSE)

# Load an example dataset ---------------
data <- read_dta("https://github.com/worldbank/r-econ-visual-library/raw/master/Library/Data/DensityCDF.dta")

# Printing the first five rows of the data to visualize its structure before data wrangling
head(data)

# Data Dictionary ---------------
  ## Data Source: 
  ## Tidy format? Yes
  ## Unit of Observation: Households
  ## Variables of interest: 
    # hh_id: Household identifier
    # post: Timing variable (pre/post treatment)
    # revenue: Agricultural Revenue


# Data wrangling ---------------
data <- data %>%
  mutate(post = as.factor(post)) %>%
  group_by(post) %>%
  mutate(mean_revenue = mean(revenue)) %>%
  ungroup()

# Printing the first five rows of the data to visualize its structure after data wrangling
head(data)

# Create a graph ---------------
ggplot(data, aes(x = revenue, color = post)) + # Use color instead of fill for the CDF
  geom_vline( # Add dashed vertical lines to indicate means
    aes(xintercept = mean_revenue, color = post), 
    linetype = "dashed", size = 0.3
    ) +
  # Add empirical cumulative density function
  stat_ecdf() + 

  theme_classic() +
  xlim(c(0, 25)) +
  labs(
    x = "Agriculture Revenue (BRL thousands)",
    y = "Cumulative Density"
  ) +
  scale_colour_discrete(labels = c("Pre-treatment", "Post-treatment")) + # Color-code by treatment status
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 15),
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    legend.position = "bottom"
    )

```
