---
pagetitle: "Density Plots: Ridgelines by group"
author: ""
date: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r DensityRidgeline, fig.path = '../docs/figure/', warning = FALSE}
# Objective ---------------
  # Create a group of Ridgeline density plots comparing distributions of health expenditures by timing and treatment status. 

# Install and load packages ---------------
packages <- c(
  "tidyverse",
  "haven",
  "ggridges"
)

# Change to install = TRUE to install the required packages
pacman::p_load(packages, character.only = TRUE, install = FALSE)

# Load an example dataset ---------------
# https://openknowledge.worldbank.org/handle/10986/25030
data <- read_dta("https://github.com/worldbank/r-econ-visual-library/raw/master/Library/Data/evaluation.dta")

# Printing the first five rows of the data to visualize its structure before data wrangling
head(data)

# Data Dictionary ---------------
  ## Data Source: 
  ## Tidy format? Yes
  ## Unit of Observation: Households
  ## Variables of interest: 
    # household_identifier: Household identifier
    # treatment_locality: Timing variable (pre/post treatment)
    # eligible: Identifier for households eligible for program of interest
    # round: Timing (baseline or follow-up) identifier 
    # health_expenditures: Annualized out of pocket health expenditures 


# Data wrangling ---------------
analysis_data <- data %>%
  filter(eligible == 1) %>% # Only keep eligible observations 
  mutate(group = interaction(round, treatment_locality), # Create variable uniquely identify by round & treatment_locality 
         group = recode_factor(group, # Label group variable accordingly 
                               `0.0` = "Before & Control",
                               `0.1` = "Before & Treated",
                               `1.0` = "After & Control",
                               `1.1` = "After & Treated"
                               ))  # Using backticks to specify the name of observations written in numbers

# Printing the first five rows of the data to visualize its structure after data wrangling
head(data)

# Create a graph ---------------
ggplot(analysis_data, aes(x = health_expenditures, y = group)) +
  stat_density_ridges(alpha = 0.6, bandwidth = 0.2) + 
  theme_ridges() + # Set theme to ridgelines 
  labs(
    x = "Health Expenditures ($)",
    y = "Group"
  ) +
  xlim(c(0, 50)) +
  theme(legend.position = "none") # Setting the legend.position to none to get rid of the legend

```


