---
pagetitle: "Density Plots"
author: ""
date: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview

Create a stacked bar charts assessing the whether there was a medical referral and drug dispensing practices of pharmacies for standardized patients with presumed (Case 1) and confirmed (Case 2) tuberculosis in India.

```{r DensityWithData, fig.path = '../docs/figure/'}
# Install and load packages ---------------
packages <- c(
  "tidyverse",
  "haven"
)

# Change to install = TRUE to install the required packages
pacman::p_load(packages, character.only = TRUE, install = FALSE)

```

# Data

- `theta_mle`: theta (MLE)
- `roster_6a8`: higest level of education

- Unit of Observation: 


```{r DensityWithData, fig.path = '../docs/figure/'}
# Load an example dataset ---------------
data <- read_dta("https://github.com/worldbank/stata-visual-library/raw/master/Library/data/density-data.dta")

# Printing the first five rows of the data to visualize its structure before data wrangling
head(data)

```

```{r DensityWithData, fig.path = '../docs/figure/', warning = FALSE, message = FALSE}
# Data wrangling ---------------
data <- data %>%
  filter(!(is.na(theta_mle) | is.na(roster_6a8))) %>% 
  mutate(
    score = theta_mle - min(theta_mle), 
    bach = (as.numeric(roster_6a8) > 4)
    ) %>%
  group_by(bach) %>%
  mutate(tot_num = n()) %>%
  ungroup()

bw <- 0.1 # setting the bandwith variable separetly for later uses 

# Using for loop to customize the dataset
for (i in c(0, 1)) {
  sub_data <- data %>% filter(bach == i)
  hist_graph <- ggplot(sub_data, aes(x = score)) + geom_histogram(binwidth = bw)
  hist_data <- ggplot_build(hist_graph)$data[[1]]
  hist_breaks <- c(hist_data$xmin, tail(hist_data$xmax, n = 1))
  
  data$bin_score[data$bach == i] <- hist_data$count[findInterval(sub_data$score, hist_breaks)]
}

# Printing the first five rows of the data to visualize its structure after data wrangling
head(data)

```

```{r DensityWithData, fig.path = '../docs/figure/'}
# Create a graph ---------------
ggplot(data, aes(x = score, colour = bach)) +
  geom_density(aes(y = ..count.. * bw)) +
  geom_density() +
  scale_color_brewer(palette = "Set2") +
  geom_point(aes(y = bin_score), size = 0.5) 

```
