---
pagetitle: "Bar Plots: Horizontal Bar Plots"
author: ""
date: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r HorizontalBarPlot, fig.path = '../docs/figure/', warning = FALSE}
# Objective ---------------
# Combine two different datasets measuring different clinics' daily time with patients, create an ascending horizontal bar chart of clinics' average daily time with patients by region and clinic types

# Install and load packages ---------------
packages <- c(
  "tidyverse",
  "haven",
  "latex2exp",
  "forcats"
)

# Change to install = TRUE to install the required packages
pacman::p_load(packages, character.only = TRUE, install = FALSE)

# Load example datasets ---------------
data1 <- read_dta("https://github.com/worldbank/r-econ-visual-library/raw/master/Library/Data/HorizontalBarPlot1.dta")
data2 <- read_dta("https://github.com/worldbank/r-econ-visual-library/raw/master/Library/Data/HorizontalBarPlot2.dta")

# Printing the first five rows of the data to visualize its structure before data wrangling
head(data1)
head(data2)

# Data Dictionary (data1) ---------------
  ## Data Source: Data Source: Das, Jishnu, Liana Woskie, Ruma Rajbhandari, Kamran Abbasi, and Ashish Jha. “Rethinking assumptions about delivery of healthcare: implications for universal health coverage.” Bmj 361 (2018).
  ## Tidy format? Yes
  ## Unit of Observation: Individual clinics
    # study: Clinic type identifier
    # hours: Total daily time seeing patients (hours)

# Data Dictionary (data2) ---------------
  ## Data Source:
  ## Tidy format? Yes
  ## Unit of Observation: Individual clinics
  ## Variables of Interest
     # study: Clinic type identifier
     # totime: Total daily time seeing patients (minutes)


# Data wrangling ---------------

# Generate hour variable from minute variable
data2 <- data2 %>% mutate(hours = tottime / 60) # Convert time variable to hourly format 

# Append two datasets
data <- bind_rows(data1, data2) # bind_rows append the two given datasets

# Printing the first five rows of the data to visualize its structure 
head(data)

data_mean <- data %>% # Collapse data by mean time spent with each patient by each clinic type
  group_by(study) %>% # Select study as unit of observation
  summarise(hours = mean(hours)) %>% # Collapse variable of interest to mean of hours
  ungroup() %>%
  mutate(study = fct_reorder(study, desc(hours))) 

# Printing the first five rows of the data to visualize its structure 
head(data_mean)

# Drop unnecessary quotes from group labels 
data_mean$study <- factor(str_replace_all(levels(data_mean$study), "\\\"", ""))
# Add newline sign (\n) before parentheses in group labels
data_mean$study <- factor(str_replace_all(levels(data_mean$study), " \\(", "\n\\("))

# Printing the first five rows of the data to visualize its structure after data wrangling
head(data_mean)

# Create a Graph ---------------
data_mean %>%
  mutate(study = fct_reorder(study, desc(hours))) %>% # Order by hours (descending)
  ggplot(aes(x = study, y = hours)) + 
  geom_bar(stat = "identity", alpha = .6, width = .4) + # Set bar width & transparency
  geom_text(
    # Setting format(round(hours, 1)) round the numbers to first decimal point
    aes(label = format(round(hours, 1), nsmall = 1)), 
    position = position_dodge(width = 0.8), 
    size = 4.5,
    hjust = -0.35 # hjust for horizontal location adjustment
    ) +
  geom_hline(yintercept = 0, alpha = 0.5) +
  coord_flip(ylim = c(0, 3)) +
  xlab("") + # setting xlab to "" without any contents between the parentheses removes the label for the x-axis
  # Using TeX to use LaTeX characters (wrapped by the dollar signs) in the plot 
  ylab(TeX("Average Daily Time Seeing Patients $\\rightarrow$")) +  
  scale_y_continuous(
    breaks = c(0, 1, 2, 3), # Set y-axis range 
    # setting labels (in accordance with the breaks) to easily interpretable labels 
    label = c('0', '1 Hour', '2 Hours', '3 Hours') 
    ) + 
  theme_classic() +
  theme(
    # element_blank() removes the given visualization. 
    # For instance, axis.line.y = element_blank removes the axis.line.y
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text = element_text(size = 12),
    axis.title.x = element_text(size = 15)
    )
  
```

