---
pagetitle: "Bar Plots: Horizontal Multiple Variables"
author: ""
date: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r HorizontalBetterbar, fig.path = '../docs/figure/'}
# Objective ---------------
# Create a group of horizontal bar charts displaying the proportion of providers that asked different questions about medical history and performed different medical exams. Stack the bar charts for questions on top of the bar charts for medical exams. 

# Install and load packages ---------------
packages <- c(
  "tidyverse",
  "haven",
  "labelled",
  "forcats"
)

# Change to install = TRUE to install the required packages
pacman::p_load(packages, character.only = TRUE, install = FALSE)

# Load an example dataset ---------------
data <- read_dta("https://github.com/worldbank/r-econ-visual-library/raw/master/Library/Data/HorizontalBetterbar.dta")

# Printing the first five rows of the data to visualize its structure before data wrangling
head(data)

# Data Dictionary ---------------
  ## Data Source: Das, Jishnu et al. “Use of standardised patients to assess quality of tuberculosis care: a pilot, cross-sectional study.” The Lancet. Infectious diseases vol. 15,11 (2015): 1305-13. doi:10.1016/S1473-3099(15)00077-8
  ## Tidy format? Yes
  ## Unit of Observation: Individual clinics
  ## Variables of interest
    # sp1_h: Dummy variable indicating whether question was asked on particular subject
    # sp1_e: Dummy variable indicating whether test was performed on particular subject

# Data wrangling ---------------

# Save variable labels in list 
data_varlabel <- unlist(var_label(data))

# Make lists of variables to be used
var_group_1 <- c()
for (i in 1:21){
  if (i == 6){ # 6 is missing in data, so skip it
    next
  } else {
    var_group_1 <- c(var_group_1, paste0("sp1_h", i)) # using paste0 to concatenate "sp1_h" and i
  }
}

var_group_2 <- c()
for (i in 1:6){  # 4 is missing in data, so skip it
  if (i == 4){
    next
  } else {
    var_group_2 <- c(var_group_2, paste0("sp1_e", i))
  }
}

# Calculate the mean for each variable
mean_data <- data %>%
  summarise_at(
    all_of(c(var_group_1, var_group_2)), 
    list(~ mean(., na.rm = TRUE)) 
    )

# Reshape the data to longer format, identifying question/exam type, and grouping questions and exams together.
fig_data <- mean_data %>%
  pivot_longer(
    all_of(c(var_group_1, var_group_2)), 
    names_to = "key", values_to = "value" # This extracts the value in each cell and assigns it an identifier from the name of the variable it comes from
    ) %>%
  mutate(
    key_label = data_varlabel[.$key], # This assigns a label to each variable from the label list we saved earlier
    group = ifelse(.$key %in% all_of(var_group_1), 1, 0), # Group variables according to lists made earlier
    key_label = fct_reorder(key_label, value)
    )

# Label for each variable
x_label <- as.character(sort(interaction(fig_data$key_label, fig_data$group))) %>%
  str_replace("\\.\\d", "") # Remove decimals from label suffix

# Printing the first five rows of the data to visualize its structure after data wrangling
head(fig_data)

# Create a plot ---------------
ggplot(fig_data, aes(x = interaction(key_label, group), y = value, label = key_label)) +
  geom_bar(
    stat = "identity", 
    # Setting position_dodge2 preserve argument to "single" maintains the total width of a single element
    width = 0.6, position = position_dodge2(width = 0.6, preserve = "single")
    ) +
  # coord_flip flips the x and y axes. This is useful when the graph is too long (horizontally) or too tall (vertically)
  coord_flip(ylim = c(0, 1)) + 
  geom_hline(yintercept = 0, alpha = 0.5) +
  geom_text(
    aes(label = format(round(value, 2), nsmall = 2)), 
    position = position_dodge2(width = 0.6, preserve = "single"), 
    hjust = -0.35
    ) +
  scale_x_discrete(labels = x_label) +
  theme_classic() +
  theme(
    # element_blank() removes the given visualization. 
    # For instance, axis.line.y = element_blank removes the axis.line.y
    axis.line = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title = element_blank()
    )

```
