---
  title: "Regression_Table"
author: ""
date: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r balance table}
# Load the following packages -------------
packages <- c("stargazer", 
              "dplyr", 
              "haven"
              )

if (!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman")
pacman::p_load(packages, character.only = TRUE)

# Load the sample data set --------------
data <- read_dta("https://github.com/worldbank/r-econ-visual-library/raw/master/Library/Data/nlsw88.dta")
dir.create("Outputs", recursive = TRUE, showWarnings = TRUE) # to create a new folder

# Run the Regressions --------------------
reg1 <- lm(wage ~ union + collgrad + ttl_exp, data)
reg2 <- lm(wage ~ union + collgrad + ttl_exp+ factor(industry), data)
reg3 <- lm(hours ~ union + collgrad + ttl_exp, data)
reg4 <- lm(hours ~ union + collgrad + ttl_exp+ factor(industry), data)

# Create the Table ----------------------
reg_table <- 
  stargazer(reg1,
            reg2,
            reg3,
            reg4,
            title = "Regression Table",
            keep = c("union", "collgrad", "ttl_exp"),
            covariate.labels = c("Union worker", # replace with labels of your choice 
                                 "College Graduate",
                                 "Total work experience (years)"),
            dep.var.labels = c("Hourly wage",
                               "Hours worked"),
            dep.var.caption = "",
            add.lines = list(c("Industry FE", "No", "Yes", "No", "Yes")),
            keep.stat = c("n", "adj.rsq"), 
            header = FALSE, 
            notes = "Standard errors in parentheses",
            out = "Outputs/regression-table.tex"
  )

## Annex ---------------------

# To successfully view the table and reproduce the outputs, open the '.tex' file in any Latex editor, and add the following syntax:  

# \documentclass{article}

# % Required packages
# \usepackage{booktabs}    % For \toprule, \midrule, \bottomrule
# \usepackage{array}       % For column types
# \usepackage{geometry}

# % Optional: adjust page margins
# \geometry{margin=1in}

# \begin{document}

# Also, at the following syntax at the end of the file:

# \end{document}
```
