---
pagetitle: "Scatter Plots: With emphasized labels"
author: ""
date: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

# Overview

```{r ScatterLabels, fig.path = '../docs/figure/', warning = FALSE}
# Install and load packages ---------------
packages <- c(
  "tidyverse",
  "ggrepel",
  "WDI",
  "forcats",
  "scales"
)

# Change to install = TRUE to install the required packages
pacman::p_load(packages, character.only = TRUE, install = FALSE)

```

# Data
The graph comes from the World Bank's World Development Indicators, pulled from the internet directly using the "WDI" package. 

https://datacatalog.worldbank.org/dataset/world-development-indicators

- `NY.GDP.PCAP.KD`: GDP per capita (constant 2010 US$)
- `iso2c`: ISO 3166-1 alpha-2 country code
- `year`: year

- Units of Observations: GDP per capita for each country per year

```{r ScatterLabels, fig.path = '../docs/figure/', warning = FALSE}
# Load an example dataset ---------------
data <- WDI(indicator = "NY.GDP.PCAP.KD", start = 1980, end = 2012)

# Printing the first five rows of the data to visualize its structure before data wrangling
head(data)

```

```{r ScatterLabels, fig.path = '../docs/figure/', warning = FALSE}
# Data wrangling ---------------
country_code <- as_tibble(WDI_data$country)

data <- data %>%
  rename(GDP = NY.GDP.PCAP.KD) %>%
  inner_join(country_code, by = "country") %>%
  filter(year %in% c(1980, 2012), region != "NA") %>%
  group_by(iso3c) %>%
  pivot_wider(names_from = "year", values_from = "GDP") %>%
  ungroup()

# Printing the first five rows of the data to visualize its structure after data wrangling
head(data)

# Saving the list of countries to stress for visualization 
country_stress <- c("USA", "CHN", "BRA", "RWA")

```

```{r ScatterLabels, fig.path = '../docs/figure/', warning = FALSE}
# Create a graph ---------------

ggplot(data, aes(x = `1980`, y = `2012`)) + # backticks used to variables written in numbers
  geom_point(aes(alpha = 0.8, color = (iso3c %in% country_stress)), show.legend = FALSE) +
  geom_abline(slope = 1, color = "gray") +
  geom_text_repel(aes(label = ifelse(iso3c %in% country_stress, iso3c, ""))) +
  scale_y_log10(
    limits = c(8e+1, 3e+5),
    breaks = c(1e+2, 1e+3, 1e+4, 1e+5),
    labels = expression(10^2, 10^3, 10^4, 10^5)
  ) +
  scale_x_log10(
    limits = c(8e+1, 3e+5),
    breaks = c(1e+2, 1e+3, 1e+4, 1e+5),
    labels = expression(10^2, 10^3, 10^4, 10^5)
  ) +
  scale_color_manual(values = c("gray", "red")) +
  labs(
    x = "GDP per capita (constant 2000 US$) in 1980",
    y = "GDP per capita (constant 2000 US$) in 2012"
  ) +
  theme_classic() +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12)
  )

```



