---
pagetitle: "Scatter Plots: Graded Confidence Intervals"
author: ""
date: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview


```{r ScatterCI, fig.path = '../docs/figure/', warning = FALSE}
# Install and load packages ---------------
packages <- c(
  "tidyverse",
  "haven",
  "latex2exp",
  "gridExtra",
  "lemon",
  "sciplot"
)

# Change to install = TRUE to install the required packages
pacman::p_load(packages, character.only = TRUE, install = FALSE)
```

# Data

This graph uses fictional data that is based on Christian, Paul, and Brian Dillon. 2018. "Growing and Learning When Consumption Is Seasonal: Long-Term Evidence From Tanzania." Demography 55 (3): 1091–1118. doi:10.1007/s13524-018-0669-4. 

- `cons_pae_m_sine`: M per AE (sine)

- Unit of Observation: 

```{r ScatterCI, fig.path = '../docs/figure/', warning = FALSE}
# Load an example dataset ---------------
data <- read_dta("https://github.com/worldbank/r-econ-visual-library/raw/master/Library/Data/ScatterCI.dta")

# Printing the first five rows of the data to visualize its structure before data wrangling
head(data)

```

```{r ScatterCI, fig.path = '../docs/figure/', warning = FALSE}
# Data wrangling ---------------

# Setting the seed to enhance the reproducibility of the work
set.seed(251668)

subdata <- data %>%
  filter(
    cons_pae_m_sine < quantile(.$cons_pae_m_sine, 0.99) & 
      cons_pae_m_sine > quantile(.$cons_pae_m_sine, 0.01)
    ) %>%
  sample_frac(0.05) # To emphasize the graded CI, 5% of obesrvations are randomly sampled

# Printing the first five rows of the data to visualize its structure after data wrangling
head(subdata)

```

```{r ScatterCI, fig.path = '../docs/figure/', warning = FALSE, message = FALSE}
# Create a graph ---------------

ggplot(subdata, aes(x = cons_pae_m_sine, y = cons_pae_sd_sine)) +
  geom_point(color = "black", alpha = 0.2, size = 0.8) +
  stat_smooth(aes(size = NA, fill = "90%"), alpha = 0.3, show.legend = TRUE, level = 0.90) +
  stat_smooth(aes(size = NA, fill = "95%"), alpha = 0.2, show.legend = TRUE, level = 0.95) +
  stat_smooth(aes(size = NA, fill = "99%"), alpha = 0.1, show.legend = TRUE, level = 0.99) +
  stat_smooth(color = "black", size = 0.8, alpha = 0.6, se = FALSE, show.legend = TRUE) +
  theme_classic() +
  scale_fill_manual(
    name = "Confidence Intervals", 
    values = c("90%" = "gray12", "95%" = "gray12", "99%" = "gray12")
    ) +
  guides(
    fill = guide_legend(override.aes = list(
      alpha = c(0.3, 0.2, 0.1),
      size = c(0, 0, 0))
      )
    ) +
  xlim(c(75, 130)) +
  ylim(c(5, 22)) +
  # Using TeX to display special characters in the labels for x-axis and y-axis
  xlab(TeX("$\\widehat{m}$")) +
  ylab(TeX("$\\widehat{s}$")) +
  theme(
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 15),
    legend.position = c(1, 0.01),
    legend.justification = c(1, 0),
    legend.key.width = grid::unit(35, "pt"),
    )

```


